### ISSUE TITLE
Implement the custom parser for Jupyter notebooks

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/sdk#150]
This is to record the demand of data scientists to have *.ipynb parsed. There are quite a few already. I guess we should merge all the code cells and interpret them as a Python script.

@juanjux Do you think it should be added to Python driver? It is going to reuse 100% of the code.

**Comment by juanjux** [comment]
Mmmm, let me take a look at the ipynb format (I've used iPython/Jupyter notebooks but never looked inside) and I'll tell you.

**Comment by abeaumont** [comment]
Jupyter notebooks are not `python` specific. It may be better to have some generic code extractor from Jupyter notebooks and use regular drivers once code's been extracted. I don't think that code extractor should be in any existing driver and it'll have to be shared for different languages. The easiest way would be to have an intermediate additional step that takes a Jupyter notebook, extracts the code, and calls the appropiate driver, but ideally we shouldn't add another step...

**Comment by juanjux** [comment]
@abeaumont yes, that's my tough too, the driver should only receive a code string. Still, it could be added in the `client-python` as a feature. There is an API for reading and writing notebooks: http://nbformat.readthedocs.io/en/latest/api.html

**Comment by vmarkovtsev** [comment]
@abeaumont Where would you place this generic extractor, inside the server? Looks like a hack to handle the notebooks, hehe. Probably we should create a "middleware" API layer which converts some files into other formats and name the new repo "jupyter-middleware".

**Comment by juanjux** [comment]
@vmarkovtsev  surely not in the server. Maybe in the `client-python`.

**Comment by abeaumont** [comment]
@vmarkovtsev exactly, it looks like a hack, that's why I don't like it. I'd also prefer to not have an additional layer too (even if it looks like the best idea to me), that's why I didn't give any solution (I don't have any at the moment).

An option would be to leave that resposibility to the client as @juanjux suggests, but I don't like it either, since you delegate language support to clients, which I don't think it should be their responsibility.

I don't know if @mcuadros or @smola have already considered this, maybe they already have an idea about how to solve it.

**Comment by juanjux** [comment]
I don't see it as delegating language support to the client, but opening the same language in another format instead of a `.py` file which it already opens.

**Comment by abeaumont** [comment]
This is out of scope, so we are delegating the code extraction to bblfsh users at the moment.
