### ISSUE TITLE
Migrate SDK to go-log

### ISSUE THREAD

**Issue by bzz** [bblfsh/sdk#315]
Use https://github.com/src-d/go-log instead of `type Logger interface` from [driver/server/logger.go](https://github.com/bblfsh/sdk/blob/master/driver/server/logger.go)

**Comment by bzz** [comment]
This change in SDK will affect both, bblfshd server and a individual drives.

**Comment by dennwc** [comment]
Let's bump the priority of this one.

We have problems with parsing logs using an existing implementation (see machinery in https://github.com/bblfsh/bblfshd/issues/298).

**Comment by creachadair** [comment]
I'm in favour of doing this, but I'm not convinced we should block fixing other issues for it. I realize the lack of structured logs makes some of the other issues more difficult to track, but unless it makes it impossible/infeasible, I'd really rather clear the functionality issues first and only then address infrastructural changes like this.

**Comment by dennwc** [comment]
@creachadair Right, I don't think we should postpone other work because of it, but it seems small enough for new team members to resolve. So I meant to raise the priority from "we'll do it sometimes when we have nothing else to do" to "someone from the new team members should pick this one if we don't have anything urgent for them to work on".

This affects all the drivers running in production/ML, and specifically our ability to diagnose failures in those deployments. I wouldn't say it makes us more likely to spot issues earlier, but it definitely would decrease the time needed to identify issues from those deployments (which are the main source of bug reports).

**Comment by kuba--** [comment]
note: `go-log` is basically wrapper on top of `logrus`, So if we use logrus (so far) the transition should be super simple.
